version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install test deps
          command: python -m pip install .[test]
      - run:
          name: Run tests
          command: python -m pytest -n 10
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test:
    jobs:
      - build_and_test

